// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Promethaion.Data;

#nullable disable

namespace Promethaion.Data.Migrations
{
    [DbContext(typeof(PAionDbContext))]
    partial class PAionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Promethaion.Core.Entities.PatternEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ball1")
                        .HasColumnType("int");

                    b.Property<int>("Ball2")
                        .HasColumnType("int");

                    b.Property<int>("Ball3")
                        .HasColumnType("int");

                    b.Property<int>("Ball4")
                        .HasColumnType("int");

                    b.Property<int>("Ball5")
                        .HasColumnType("int");

                    b.Property<int>("Ball6")
                        .HasColumnType("int");

                    b.Property<int?>("BonusBall")
                        .HasColumnType("int");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrawNumber")
                        .HasColumnType("int");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("DrawDate");

                    b.HasIndex("DrawNumber", "GameName")
                        .IsUnique();

                    b.ToTable("DrawResults");
                });

            modelBuilder.Entity("Promethaion.Core.Entities.PatternForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualDrawResultId")
                        .HasColumnType("int");

                    b.Property<int>("Ball1")
                        .HasColumnType("int");

                    b.Property<int>("Ball2")
                        .HasColumnType("int");

                    b.Property<int>("Ball3")
                        .HasColumnType("int");

                    b.Property<int>("Ball4")
                        .HasColumnType("int");

                    b.Property<int>("Ball5")
                        .HasColumnType("int");

                    b.Property<int>("Ball6")
                        .HasColumnType("int");

                    b.Property<int?>("BonusBall")
                        .HasColumnType("int");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MatchCount")
                        .HasColumnType("int");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PerBallConfidenceJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetDrawNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActualDrawResultId");

                    b.HasIndex("TargetDrawNumber");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("Promethaion.Core.Entities.TrainingMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageMatchCount")
                        .HasColumnType("float");

                    b.Property<string>("DiagnosticsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBestVersion")
                        .HasColumnType("bit");

                    b.Property<double>("LogLoss")
                        .HasColumnType("float");

                    b.Property<double>("MacroAccuracy")
                        .HasColumnType("float");

                    b.Property<double>("MeanAbsoluteError")
                        .HasColumnType("float");

                    b.Property<double>("MicroAccuracy")
                        .HasColumnType("float");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PipelineName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<double>("RSquared")
                        .HasColumnType("float");

                    b.Property<double>("RootMeanSquaredError")
                        .HasColumnType("float");

                    b.Property<int>("TestSetSize")
                        .HasColumnType("int");

                    b.Property<DateTime>("TrainedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainingSetSize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PipelineName", "IsBestVersion");

                    b.ToTable("ModelMetrics");
                });

            modelBuilder.Entity("Promethaion.Core.Entities.PatternForecast", b =>
                {
                    b.HasOne("Promethaion.Core.Entities.PatternEvent", "ActualResult")
                        .WithMany()
                        .HasForeignKey("ActualDrawResultId");

                    b.Navigation("ActualResult");
                });
#pragma warning restore 612, 618
        }
    }
}
