using System;
using System.Collections.Generic;
using System.Text;

namespace Promethaion.Core.Entities
{
    /// <summary>
    /// A stored prediction generated by the ensemble engine for future results.
    /// </summary>
    public class PatternForecast
    {
        public int Id { get; set; }
        public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

        /// <summary>Which draw this prediction is targeting.</summary>
        public int TargetDrawNumber { get; set; }

        // Predicted main balls (sorted).
        public int Ball1 { get; set; }
        public int Ball2 { get; set; }
        public int Ball3 { get; set; }
        public int Ball4 { get; set; }
        public int Ball5 { get; set; }
        public int Ball6 { get; set; }
        public int? BonusBall { get; set; }

        /// <summary>Overall ensemble confidence [0–1].</summary>
        public double ConfidenceScore { get; set; }

        /// <summary>JSON-serialised per-number confidence scores.</summary>
        public string PerBallConfidenceJson { get; set; } = "{}";

        /// <summary>Model version tag that produced this prediction.</summary>
        public string ModelVersion { get; set; } = "v1";

        /// <summary>Actual draw result, if draw has happened.</summary>
        public int? ActualDrawResultId { get; set; }
        public PatternEvent? ActualResult { get; set; }

        /// <summary>How many numbers matched the actual draw.</summary>
        public int? MatchCount { get; set; }

        public int[] Balls => [Ball1, Ball2, Ball3, Ball4, Ball5, Ball6];
    }
}
